"use strict";

/* ============================================================
   FLAVOR — couche d'habillage cohérente des PNJ
   S'applique APRÈS génération, sur les 3 éditions.
   Objectif : chaque PNJ semble unique sans jamais être incohérent.

   Tout est filtré par contexte (niveau, profession, faction) :
   un samouraï corpo n'a ni le style, ni l'âge, ni les manies
   d'un ganger des Barrens. On tire dans des pools pondérés par
   des « tags » de profession plutôt que dans une grande table à plat.

   Le moteur range les détails dans pnj.flavor = { age, signe,
   manie, motivation, style }. L'affichage les lit depuis là.
   ============================================================ */

const Flavor = {
  /* ----------------------------------------------------------
     CLASSIFICATION : on dérive des « tags » depuis la profession.
     Ces tags pilotent ensuite la sélection des détails.
  ---------------------------------------------------------- */
  _tagRules: [
    {
      tag: "gang",
      match: [
        "Ganger",
        "Go-ganger",
        "Gang",
        "Halloweeners",
        "Ancients",
        "Ork Rights",
      ],
    },
    {
      tag: "corpo",
      match: [
        "corpo",
        "Renraku",
        "Ares",
        "Aztechnology",
        "Séraphin",
        "Samouraï rouge",
        "Espion industriel",
        "VIP",
        "Corporations",
      ],
    },
    {
      tag: "police",
      match: [
        "Flic",
        "Knight Errant",
        "Lone Star",
        "SWAT",
        "Détective",
        "anti-magie",
        "Maintien",
      ],
    },
    {
      tag: "crime",
      match: [
        "Mafia",
        "Yakuza",
        "Triade",
        "Vory",
        "Koshari",
        "Capo",
        "Gros bras",
        "Wakagashira",
        "Soldat Mafia",
      ],
    },
    {
      tag: "militaire",
      match: [
        "Soldat",
        "Commando",
        "Mercenaire",
        "Forces spéciales",
        "Pilote militaire",
        "Rigger militaire",
        "renseignement",
      ],
    },
    {
      tag: "rue",
      match: ["Voyou", "Décérébré", "Sans-abri", "Dealer", "Foule", "Barrens"],
    },
    {
      tag: "ombre",
      match: [
        "Assassin",
        "Cambrioleur",
        "Contrebandier",
        "Passeur",
        "Faussaire",
        "Trafiquant",
        "Pilote de location",
      ],
    },
    {
      tag: "magique",
      match: ["Mage", "Chaman", "Adepte", "Initié", "éveillé", "Magogang"],
    },
    {
      tag: "matrice",
      match: [
        "Decker",
        "Technomancien",
        "Technicien matriciel",
        "contre-mesures",
        "Hacker",
      ],
    },
    { tag: "tech", match: ["Rigger", "Technicien", "Chimiste", "Mécanique"] },
    {
      tag: "civil",
      match: ["Civil", "Travailleur", "docker", "usine", "ordinaire"],
    },
  ],

  /* Mots-clés supplémentaires propres aux rôles de contacts,
     mappés sur les tags existants. Complète _tagRules sans le réécrire. */
  _contactRoleTags: {
    corpo: ["Cadre", "Johnson", "corpo"],
    crime: [
      "Consiglieri",
      "Receleur",
      "Fixer",
      "Intermédiaire",
      "identités",
      "Mafia",
    ],
    police: ["sécurité véreux", "Enquêteur", "Avocat", "Flic"],
    militaire: ["DocWagon", "combat"],
    rue: [
      "Barman",
      "bar",
      "Pharmacien",
      "Aumônier",
      "Prêtre",
      "Doc des rues",
      "gang",
    ],
    ombre: ["Contrebandier", "Passeur", "retraite", "Armurier"],
    magique: ["Mage", "Chaman", "talismans", "NAN", "Amérindiennes"],
    matrice: ["Decker", "Hacker", "numérique", "Paradis"],
    tech: [
      "Mécanicien",
      "Chirurgien",
      "cyberware",
      "Médecin",
      "Professeur",
      "Rigger",
    ],
    civil: ["Journaliste"],
  },

  tagsFor(pnj) {
    const proRating = pnj.archetype || "";
    const spec = pnj.special || "";
    const role = pnj.role || "";
    const hay = `${proRating} ${spec} ${role}`;
    const tags = new Set();
    for (const rule of this._tagRules) {
      if (rule.match.some((m) => hay.includes(m))) tags.add(rule.tag);
    }
    // Compléter avec les mots-clés de rôles de contacts
    for (const [tag, kws] of Object.entries(this._contactRoleTags)) {
      if (kws.some((k) => hay.includes(k))) tags.add(tag);
    }
    if (tags.size === 0) tags.add("rue");
    return tags;
  },

  /* ----------------------------------------------------------
     ÂGE — plausible selon le niveau d'expérience.
     Niveau bas = souvent jeune ; niveau élevé = vétéran.
     On ramène prof (0-6 SR5/Anarchy) ou rang (Anarchy) sur 0-1.
  ---------------------------------------------------------- */
  _ageFor(pnj) {
    let lvl = 0.4;
    if (typeof pnj.proRating === "number") lvl = Utils.clamp(pnj.proRating / 6, 0, 1);
    else if (pnj.tier) {
      const map = {
        Figurant: 0.2,
        "Figurant d'élite": 0.5,
        Lieutenant: 0.7,
        Boss: 0.9,
      };
      lvl = map[pnj.tier] ?? 0.4;
    }
    // Base 19 ans + jusqu'à ~28 ans selon expérience, ± bruit
    const base = 19 + Math.round(lvl * 26);
    const age = base + Utils.randInt(-3, 5);
    // Elfes et certaines métavariantes vivent plus vieux : on ne plafonne pas
    return Utils.clamp(age, 16, 71);
  },

  /* ----------------------------------------------------------
     POOLS DE DÉTAILS — indexés par tag.
     'any' = fond commun toujours disponible.
  ---------------------------------------------------------- */
  _signes: {
    any: [
      "cicatrice à la lèvre",
      "regard fuyant",
      "voix éraillée",
      "mâchoire serrée",
      "tatouage discret au cou",
      "doigts jaunis",
      "démarche assurée",
      "rire nerveux",
      "parfum trop fort pour masquer autre chose",
      "vieille brûlure sur la main gauche",
      "regard qui s'attarde une seconde de trop",
      "sourire asymétrique",
      "tic à la paupière",
      "ongles impeccablement entretenus",
      "accent difficile à situer",
      "mains calleuses malgré une tenue élégante",
      "yeux rougis par le manque de sommeil",
      "air constamment sur ses gardes",
      "sourcils constamment froncés",
      "cerne sous un seul œil",
      "voix trop basse pour son gabarit",
      "manière de traîner sur les fins de phrase",
      "regard qui jauge la valeur de tout",
      "dents du bonheur",
      "petite cicatrice à l'arcade",
      "tatouage à moitié effacé au laser",
      "poignée de main trop ferme",
      "clignements d'yeux trop rares",
      "façon de pencher la tête pour écouter",
      "vieux tic de langage répété",
      "narine déviée par une ancienne fracture",
      "mains qui ne tiennent jamais en place",
      "sourire qui arrive une seconde trop tard",
      "regard qui revient sans cesse à la porte",
      "voix rauque de gros fumeur",
      "posture affaissée d'un dos fatigué",
      "traces d'un vieux bronzage de chantier",
      "accent de quartier qu'il tente de gommer",
    ],
    gang: [
      "tatouages de gang aux phalanges",
      "couleurs du gang sur la veste",
      "cicatrice rituelle",
      "crête colorée",
      "piercings multiples",
      "dents en métal",
      "graffitis personnels sur son équipement",
      "couleurs du gang discrètement dissimulées",
      "vieilles fractures mal ressoudées",
      "implant bon marché visible",
      "odeur de BTL ou de cram",
      "mains couvertes de cicatrices de bagarre",
      "chrome de pacotille mal greffé",
      "bras visiblement câblé pour la baston",
      "bandana aux couleurs délavées",
      "cicatrice de balle mal recousue",
      "tag du gang tatoué dans le cou",
      "cran d'arrêt qui dépasse de la poche",
      "phalanges tuméfiées",
      "boucle d'oreille trophée",
      "veste couverte de patchs cousus main",
      "regard qui cherche la bagarre",
      "collier de douilles",
      "brûlures de cigarette volontaires",
      "dent en or gagnée à un rival",
      "surnom de gang tatoué sur l'avant-bras",
      "baskets hors de prix mal assorties",
      "coupe de cheveux marquant l'allégeance",
      "vieux flingue glissé dans le pantalon",
      "sourire fanfaron",
      "scarifications comptant ses victimes",
      "démarche chaloupée de meneur",
    ],
    corpo: [
      "costume impeccable",
      "badge corpo agrafé",
      "montre hors de prix",
      "coupe nette réglementaire",
      "lentilles teintées de marque",
      "posture droite",
      "sourire professionnel parfaitement calibré",
      "implant de communication discret à l'oreille",
      "manucure impeccable",
      "odeur d'un parfum de luxe",
      "vêtements toujours légèrement trop neufs",
      "air perpétuellement pressé",
      "cravate d'un rouge calculé",
      "commlink dernier cri au poignet",
      "peau lissée par les traitements anti-âge",
      "dents parfaitement alignées et blanchies",
      "chaussures cirées au miroir",
      "voix posée de communicant entraîné",
      "épinglette de fidélité pour ancienneté",
      "stylo de luxe dans la poche de poitrine",
      "gestes mesurés de réunion",
      "regard qui évalue la valeur marchande",
      "mallette biométrique jamais lâchée",
      "sourire figé de photo corporate",
      "montre synchronisée sur trois fuseaux",
      "manteau de coupe intemporelle",
      "aucun pli, aucune tache, jamais",
      "lentilles RA affichant discrètement des données",
      "parfum unisexe hors de prix",
      "diction sans le moindre accent",
    ],
    police: [
      "coupe réglementaire",
      "regard qui balaye la pièce",
      "main jamais loin de l'étui",
      "insigne visible",
      "carrure imposante",
      "vieille blessure qui gêne certains mouvements",
      "yeux qui ne cessent de balayer les angles morts",
      "uniforme légèrement usé mais entretenu",
      "mâchoire serrée en permanence",
      "odeur de café et de fatigue",
      "regard entraîné à repérer les mensonges",
      "cals de tir sur l'index",
      "brassard réglementaire à demi caché",
      "posture prête à dégainer",
      "vieux gilet pare-balles sous la veste",
      "cicatrice de couteau à l'avant-bras",
      "façon de se placer face aux issues",
      "menottes accrochées à la ceinture",
      "voix habituée à donner des ordres",
      "regard qui note les plaques",
      "chaussures conçues pour courir",
      "sourire de façade en interrogatoire",
      "oreillette de liaison radio",
      "carnet de notes usé jusqu'à la corde",
      "démarche pesante de patrouilleur",
      "yeux cernés des services de nuit",
      "insigne dissimulé en civil",
      "main qui frôle l'arme par réflexe",
    ],
    crime: [
      "bague chevalière voyante",
      "complet sombre",
      "cure-dent permanent",
      "regard de tueur calme",
      "tatouage d'allégeance caché",
      "costume qui cache mal un gilet pare-balles",
      "bijoux chargés de symboles familiaux",
      "sourire qui n'atteint jamais les yeux",
      "mains impeccablement manucurées",
      "cicatrice ancienne soigneusement dissimulée",
      "montre suisse ostentatoire",
      "cigare éteint entre les doigts",
      "gourmette gravée d'initiales",
      "voix douce qui inquiète",
      "manteau long dissimulant une arme",
      "regard qui pèse la loyauté",
      "manières impeccables d'homme d'honneur",
      "tatouage traditionnel dépassant du col",
      "chevalière frappée d'un blason",
      "silences calculés avant chaque réponse",
      "sourire qui promet des représailles",
      "petit carnet de dettes tenu à jour",
      "parfum de cuir et de tabac cher",
      "garde du corps jamais loin",
      "poignée de main qui teste la poigne",
      "regard qui n'oublie aucun visage",
      "verre d'alcool ambré à la main",
      "diction posée de parrain",
    ],
    militaire: [
      "posture militaire",
      "cicatrices de combat",
      "tatouage d'unité",
      "regard vide du vétéran",
      "rangers cirées",
      "cheveux coupés par habitude plutôt que par règlement",
      "vieilles prothèses militaires",
      "regard qui mesure systématiquement les distances",
      "corps couvert de cicatrices anciennes",
      "matériel entretenu avec obsession",
      "posture au garde-à-vous inconscient",
      "plaques d'identité sous la chemise",
      "cicatrice d'éclat sur la joue",
      "coupe rase par pur réflexe",
      "regard qui évalue les angles de tir",
      "tatouage régimentaire sur l'épaule",
      "main calleuse habituée au fusil",
      "démarche assurée en terrain découvert",
      "montre tactique éraflée",
      "voix sèche d'ordre bref",
      "vieilles brûlures de poudre",
      "réflexe de compter ses munitions",
      "posture qui ne tourne jamais le dos",
      "cals aux mains dessinés par le paquetage",
      "cerne du sommeil rationné",
      "cicatrices alignées comme un décompte",
      "prothèse militaire sobre et fonctionnelle",
      "regard vide fixé sur un souvenir",
    ],
    rue: [
      "vêtements râpés",
      "regard méfiant",
      "ongles sales",
      "manteau trop grand",
      "odeur de synthé bon marché",
      "vêtements adaptés à plusieurs saisons à la fois",
      "odeur de pluie, de fumée et de plastique",
      "regard constamment attiré par la nourriture",
      "visage marqué par les nuits dehors",
      "matériel récupéré et rafistolé",
      "chaussures dépareillées trouvées ici et là",
      "sac plastique bourré de possessions",
      "peau tannée par la vie dehors",
      "toux persistante de bronches abîmées",
      "regard qui guette la charité",
      "plusieurs couches de vêtements crasseux",
      "ongles noircis impossibles à nettoyer",
      "odeur de fumée de barils",
      "cheveux emmêlés depuis longtemps",
      "démarche prudente sur des pieds douloureux",
      "vieux manteau militaire troué",
      "regard baissé pour ne pas provoquer",
      "réflexe de cacher le peu qu'il a",
      "gerçures aux mains l'hiver",
      "sourire édenté",
      "bouteille de synthé jamais loin",
      "carton plié servant de lit sous le bras",
      "yeux fatigués de vigilance permanente",
    ],
    ombre: [
      "visage qu'on oublie aussitôt",
      "gants en toute saison",
      "capuche relevée",
      "silhouette passe-partout",
      "voix neutre",
      "aucun détail ne semble mémorable",
      "vêtements qui changent selon le quartier",
      "yeux toujours cachés derrière quelque chose",
      "gestes économes et précis",
      "matériel porté de façon parfaitement fonctionnelle",
      "vêtements sans aucune étiquette",
      "visage passe-partout impossible à décrire",
      "regard qui repère les caméras d'un coup d'œil",
      "gants fins portés en toute discrétion",
      "voix modulée pour ne rien trahir",
      "silhouette qui se fond dans la foule",
      "gestes lents et parfaitement contrôlés",
      "démarche silencieuse presque féline",
      "manteau réversible aux deux teintes neutres",
      "aucun bijou, aucun signe distinctif",
      "capuche relevée dès qu'une caméra apparaît",
      "réflexe de repérer chaque issue",
      "regard qui évite les objectifs",
      "poches nombreuses et discrètes",
      "attitude étudiée pour ne pas marquer les mémoires",
      "chaussures souples aux semelles muettes",
      "façon de rester dans les angles morts",
      "mains toujours prêtes mais jamais visibles",
    ],
    magique: [
      "fétiches autour du cou",
      "yeux qui semblent voir ailleurs",
      "symboles tracés sur la peau",
      "calme déroutant",
      "murmures inaudibles",
      "regard distrait comme à l'écoute de quelque chose",
      "odeur d'encens ou d'herbes",
      "bijoux chargés de symboles personnels",
      "présence étrangement apaisante ou inquiétante",
      "petits objets rituels cousus dans les vêtements",
      "amulette dissimulée sous la chemise",
      "regard qui suit des lueurs invisibles",
      "murmures d'incantation à peine audibles",
      "tatouages tracés selon un motif rituel",
      "odeur d'herbes séchées et de cire",
      "bagues gravées de glyphes",
      "gestes esquissés dans le vide",
      "calme troublant en toute circonstance",
      "petit fétiche serré au creux de la main",
      "yeux qui se voilent par instants",
      "cicatrices rituelles sur les avant-bras",
      "collier de perles chargées de sens",
      "façon de saluer un totem invisible",
      "poudre colorée sous les ongles",
      "regard fixé au-delà des murs",
      "chuchotements adressés à personne",
      "bracelet de plumes et d'osselets",
      "présence qui met la peau à vif",
    ],
    matrice: [
      "datajack visible à la tempe",
      "yeux cybernétiques scintillants",
      "tics nerveux des doigts",
      "teint blafard d'insomniaque",
      "lunettes RA jamais retirées",
      "cernes profondes éclairées par des interfaces RA",
      "mouvements oculaires suivant des fenêtres invisibles",
      "vêtements équipés de multiples ports et câbles",
      "brûlures de contact près des implants",
      "gestes qui semblent manipuler des objets inexistants",
      "reflets d'interfaces dans les pupilles",
      "doigts qui pianotent sur des touches absentes",
      "datajack encrassé à la tempe",
      "teint gris des nuits sur la Matrice",
      "regard décroché du monde réel",
      "cernes lumineuses des lunettes RA",
      "commlink couvert d'autocollants de crews",
      "câbles optiques dépassant du col",
      "réflexe de scanner les réseaux d'une pièce",
      "yeux qui suivent des fenêtres invisibles",
      "tics nerveux des paupières",
      "voix trop rapide à force de penser vite",
      "brûlures de contact autour des prises",
      "posture avachie de longues connexions",
      "sourire absent en pleine conversation RA",
      "ongles rongés jusqu'au sang",
      "odeur de plastique chaud et d'énergie",
      "regard fixé sur un point que nul ne voit",
    ],
    tech: [
      "taches de cambouis",
      "outils accrochés à la ceinture",
      "lunettes-loupe relevées",
      "doigts couverts de pansements",
      "odeur d'huile, d'ozone ou de soudure",
      "vêtements brûlés par endroits",
      "poches remplies de pièces détachées",
      "implants réparés plusieurs fois",
      "mains noircies malgré les lavages",
      "traces de graisse jusqu'aux coudes",
      "multitool accroché à la ceinture",
      "brûlures de fer à souder sur les doigts",
      "loupe frontale relevée sur le front",
      "poches débordant de vis et de connecteurs",
      "ongles cassés par le travail manuel",
      "odeur d'ozone et de flux de soudure",
      "cals au bout des doigts",
      "combinaison constellée de pièces récupérées",
      "regard qui démonte tout mentalement",
      "chiffon graisseux jamais loin",
      "petites cicatrices de coupures d'atelier",
      "lunettes de protection rayées",
      "réflexe de tapoter les machines",
      "bracelet antistatique au poignet",
      "taches de peinture et de mastic",
      "gants coupés aux doigts pour la précision",
      "odeur de café froid d'atelier",
    ],
    civil: [
      "allure quelconque",
      "vêtements de travail usés",
      "air fatigué",
      "alliance au doigt",
      "badge professionnel usé",
      "vêtements choisis pour durer",
      "air préoccupé par autre chose",
      "petites économies visibles dans chaque détail",
      "commlink ancien soigneusement entretenu",
      "sac de courses réutilisable plié dans la poche",
      "chaussures confortables d'usage quotidien",
      "montre bon marché mais fiable",
      "regard fatigué de fin de journée",
      "vêtements repassés avec soin malgré l'usure",
      "badge d'employé encore agrafé",
      "photo de famille en fond d'écran",
      "posture voûtée des trajets quotidiens",
      "alliance simple et discrète",
      "petits gestes économes appris par nécessité",
      "cabas contenant un repas fait maison",
      "regard qui évite les ennuis",
      "carte de transport usée jusqu'au trou",
      "sourire poli de service",
      "cernes de nuits trop courtes",
      "veste passe-partout achetée en solde",
      "trousseau de clés qui cliquette",
      "air discret de qui veut passer inaperçu",
    ],
  },

  _manies: {
    any: [
      "tapote du pied quand il attend",
      "répète la dernière phrase de son interlocuteur",
      "ne quitte jamais une pièce sans repérer les sorties",
      "compte sa monnaie deux fois",
      "siffle entre ses dents",
      "évite systématiquement le contact visuel",
      "termine les verres abandonnés",
      "observe les mains avant les visages",
      "s'interrompt au milieu de ses phrases",
      "hausse les épaules avant de mentir",
      "parle aux objets comme s'ils répondaient",
      "compte mentalement les personnes présentes",
      "demande toujours l'heure alors qu'il possède un commlink",
      "range machinalement ce qui traîne devant lui",
      "coupe sa nourriture en parts égales",
      "vérifie deux fois si la porte est verrouillée",
      "reformule les questions avant d'y répondre",
      "garde une main dans la poche",
      "tapote la table du bout des ongles",
      "regarde l'heure sans vraiment la lire",
      "répond par une question",
      "s'assoit toujours au même type de place",
      "joue avec un objet dans sa main",
      "note mentalement qui entre et qui sort",
      "fait craquer ses doigts avant de parler",
      "évite de dire les noms à voix haute",
      "garde le dos droit quoi qu'il arrive",
      "termine les phrases des autres",
      "sourit pour gagner du temps",
      "recompte toujours ce qu'on lui rend",
      "fixe un point derrière son interlocuteur",
    ],
    gang: [
      "crache par terre pour marquer son mépris",
      "joue avec un cran d'arrêt",
      "parle en argot de gang",
      "défie du regard par réflexe",
      "évalue immédiatement l'appartenance de chacun",
      "cherche toujours à savoir d'où viennent les gens",
      "teste les inconnus avec des insultes amicales",
      "marque son territoire sans y penser",
      "ne supporte pas qu'on touche à sa veste",
      "fait tourner son flingue entre ses doigts",
      "exhibe son chrome pour intimider",
      "appelle les flics « la Star » avec mépris",
      "toise les nouveaux de haut en bas",
      "cogne son poing dans sa paume",
      "parle plus fort que nécessaire",
      "revendique son quartier à tout propos",
      "cherche à savoir qui commande",
      "réagit au moindre manque de respect",
      "tape dans le dos un peu trop fort",
      "affiche ses armes ostensiblement",
      "traite ses proches de « frère » ou « sœur »",
      "défie du regard sans raison",
      "raconte ses coups d'éclat en boucle",
      "crache quand un rival est mentionné",
      "vérifie qui porte quelles couleurs",
      "menace pour rire, à moitié",
      "compte ses ennemis à voix haute",
      "graffe son blaze partout",
      "réclame le respect avant tout",
      "cherche l'embrouille quand il s'ennuie",
    ],
    corpo: [
      "consulte son commlink toutes les deux minutes",
      "corrige la moindre faute de langage",
      "refuse les poignées de main",
      "parle en jargon corporatiste",
      "transforme toute conversation en réunion",
      "prend des notes même lorsqu'il n'y a rien à noter",
      "utilise des acronymes incompréhensibles",
      "s'excuse avant de formuler une menace",
      "parle de lui à travers sa corporation",
      "vérifie l'orthographe de tout message",
      "planifie chaque minute de sa journée",
      "cite des chiffres pour appuyer chaque phrase",
      "reformule en jargon de management",
      "consulte ses mails en pleine conversation",
      "évalue le retour sur investissement de tout",
      "distribue des cartes de visite virtuelles",
      "s'excuse pour mieux imposer sa volonté",
      "ramène tout à un tableau de bord",
      "note les faiblesses de ses interlocuteurs",
      "parle en « nous » au nom de la corpo",
      "fixe des « objectifs » à une simple discussion",
      "vérifie sa tenue dans chaque reflet",
      "traite les pauses comme des réunions",
      "refuse de perdre du temps en banalités",
      "programme un rappel pour tout",
      "sourit exactement le temps requis",
      "évalue qui vaut la peine d'être salué",
    ],
    police: [
      "mémorise les visages",
      "annonce ses intentions comme un rapport",
      "garde une distance tactique",
      "tutoie pour intimider",
      "pose des questions comme lors d'un interrogatoire",
      "retient automatiquement les plaques et les visages",
      "se place toujours dos au mur",
      "observe les mains avant les paroles",
      "demande des pièces d'identité par réflexe",
      "récite les faits comme un procès-verbal",
      "surveille les mains de tout le monde",
      "se souvient des visages des semaines après",
      "annonce ce qu'il va faire avant de le faire",
      "garde une distance de sécurité",
      "tutoie pour déstabiliser",
      "cherche la faille dans chaque récit",
      "note les incohérences à voix basse",
      "se place toujours entre la cible et la sortie",
      "traite chaque bruit comme une menace",
      "vérifie les alibis même hors service",
      "compte les issues d'une pièce en entrant",
      "garde son arme du côté du mur",
      "pose deux fois la même question autrement",
      "observe qui transpire quand il parle",
      "reste debout pour dominer l'échange",
      "raconte de vieilles affaires non résolues",
    ],
    crime: [
      "ne tourne jamais le dos à la porte",
      "offre toujours à boire d'abord",
      "parle à voix basse",
      "teste la loyauté par de petites faveurs",
      "laisse de longs silences avant de répondre",
      "fait répéter les promesses",
      "appelle tout le monde par un diminutif",
      "offre de petits cadeaux lourds de sens",
      "fait toujours attendre avant de recevoir",
      "offre à boire pour jauger l'invité",
      "ne parle jamais affaires au téléphone",
      "rappelle discrètement les dettes passées",
      "laisse ses hommes parler à sa place",
      "sourit quand il est le plus dangereux",
      "teste par de petites faveurs demandées",
      "parle par sous-entendus",
      "n'oublie jamais un affront",
      "récompense la loyauté sur-le-champ",
      "fait répéter les engagements devant témoin",
      "garde un ton posé même en menaçant",
      "s'informe de la famille de ses interlocuteurs",
      "règle l'addition avant qu'on la demande",
      "ne tourne jamais le dos à la salle",
      "laisse planer un long silence",
      "appelle chacun par un diminutif choisi",
      "connaît toujours un secret sur vous",
    ],
    militaire: [
      "vérifie son arme par réflexe",
      "parle en termes de mission",
      "se lève à heure fixe",
      "évalue chaque pièce comme un terrain",
      "compte inconsciemment les sorties",
      "observe les lignes de tir potentielles",
      "mange rapidement, même au calme",
      "emploie un vocabulaire tactique",
      "démonte et remonte son arme en réfléchissant",
      "parle en termes d'objectifs et de risques",
      "se réveille avant l'aube par habitude",
      "évalue chaque salle comme un champ de tir",
      "vérifie les sorties dès qu'il entre",
      "mange vite et sans un mot",
      "range son matériel au millimètre",
      "compte ses cartouches machinalement",
      "attribue des rôles à tout le groupe",
      "reste en alerte même au repos",
      "traduit tout en langage de mission",
      "sécurise son périmètre avant de se poser",
      "juge les gens à leur discipline",
      "dort d'un œil, toujours prêt",
      "cite des règles d'engagement",
      "repère les couvertures potentielles",
      "garde le silence radio par principe",
      "salue d'un signe de tête sec",
    ],
    rue: [
      "mendie un clope à tout le monde",
      "garde la tête basse",
      "planque sa nourriture",
      "sursaute au moindre bruit",
      "ramasse tout ce qui pourrait servir",
      "surveille les poubelles intéressantes",
      "cache ses biens sans s'en rendre compte",
      "remercie excessivement pour les petits gestes",
      "ramasse tout ce qui pourrait servir",
      "quémande une clope ou un nuyen",
      "cache sa nourriture au fond d'une poche",
      "sursaute au moindre mouvement brusque",
      "connaît chaque recoin où se planquer",
      "remercie trois fois pour un rien",
      "surveille les poubelles pleines",
      "évite le regard des uniformes",
      "dort d'un sommeil léger et bref",
      "raconte des histoires pour attendrir",
      "compte ses maigres pièces sans cesse",
      "repère qui pourrait donner un peu",
      "planque ses affaires en plusieurs endroits",
      "mendie avec un boniment bien rodé",
      "fuit dès qu'un ennui approche",
      "partage peu, se méfie beaucoup",
      "récupère les restes des tables voisines",
      "se fond dans le décor pour disparaître",
    ],
    ombre: [
      "efface ses traces machinalement",
      "change d'itinéraire sans raison",
      "ne donne jamais son vrai nom",
      "paie toujours en liquide intraçable",
      "s'assied toujours face aux sorties",
      "retient les noms sans jamais donner le sien",
      "observe les caméras avant les personnes",
      "laisse les autres parler en premier",
      "efface machinalement ses empreintes",
      "change d'itinéraire sans raison apparente",
      "ne donne jamais son vrai nom",
      "paie en liquide intraçable",
      "s'assoit dos au mur, face aux sorties",
      "retient les noms sans livrer le sien",
      "repère les caméras avant les gens",
      "vérifie qui l'a suivi dans la rue",
      "prépare toujours une porte de sortie",
      "coupe la conversation dès qu'elle dérape",
      "ne se déplace jamais sans plan B",
      "brouille les pistes par habitude",
      "note les habitudes des autres",
      "garde ses cartes cachées jusqu'au bout",
      "teste chaque nouvelle recrue discrètement",
      "range son visage dans l'ombre",
      "quitte une pièce sans qu'on le remarque",
      "vérifie la présence de micros par réflexe",
    ],
    magique: [
      "touche ses fétiches avant d'agir",
      "lit l'aura des gens sans le dire",
      "évite le fer quand il peut",
      "marmonne des formules",
      "observe le vide pendant quelques secondes",
      "évite certains lieux sans explication",
      "parle de coïncidences comme de certitudes",
      "remercie des esprits invisibles",
      "trace des signes discrets dans l'air",
      "consulte un objet rituel avant de décider",
      "murmure une prière avant l'action",
      "observe les ombres comme si elles bougeaient",
      "refuse de traverser certains seuils",
      "garde toujours du sel ou de l'encens sur lui",
      "salue silencieusement les lieux qu'il visite",
      "interprète les rêves des autres",
      "s'écarte des courants d'air froids",
      "parle aux animaux comme à des égaux",
      "évite de prononcer le nom des esprits",
      "dessine un cercle imaginaire avant d'agir",
      "lit des présages dans les détails infimes",
      "touche du bois, du fer ou de la terre selon le cas",
      "s'isole un instant pour « écouter »",
      "garde les yeux mi-clos en pleine lumière",
      "récite une litanie pour se concentrer",
      "refuse certains cadeaux sans s'expliquer",
    ],
    matrice: [
      "décrit le monde réel en termes de données",
      "tape dans le vide comme sur un clavier",
      "méfiant de toute caméra",
      "parle trop vite",
      "cherche un réseau avant une sortie de secours",
      "compare les gens à des logiciels",
      "reste silencieux pendant des conversations RA",
      "perd le fil du monde réel",
      "jauge le niveau de Bruit d'une pièce par réflexe",
      "surnomme la glace des serveurs qu'il a forcés",
      "garde son commlink en mode silencieux paranoïaque",
      "décrit le réel en termes de données",
      "tape dans le vide comme sur un clavier",
      "se méfie de chaque caméra",
      "parle trop vite pour être suivi",
      "cherche un réseau avant une sortie",
      "compare les gens à des logiciels",
      "reste muet pendant des échanges RA",
      "perd le fil du monde physique",
      "sauvegarde tout, deux fois",
      "chiffre même ses listes de courses",
      "consulte les indices avant les visages",
      "coupe court dès que le sujet quitte la tech",
      "réagit à des notifications que nul n'entend",
      "efface son historique par réflexe",
      "traque la moindre latence dans une conversation",
      "vérifie le niveau de Bruit d'une pièce",
      "surnomme la glace des serveurs qu'il a forcés",
      "recharge ses appareils dès qu'il le peut",
    ],
    tech: [
      "démonte un objet pour comprendre",
      "garde toujours un tournevis",
      "nomme ses drones et véhicules",
      "graisse ses outils en réfléchissant",
      "diagnostique tout ce qu'il voit",
      "écoute les machines avant les gens",
      "parle à ses outils",
      "récupère des pièces sans valeur apparente",
      "tapote les appareils qui hésitent",
      "improvise une réparation avec trois fois rien",
      "trie sa quincaillerie par habitude",
      "évalue le poids d'un métal au toucher",
      "explique le fonctionnement même sans qu'on demande",
      "range ses vis dans de vieilles boîtes",
      "renifle une panne électrique avant de la voir",
      "modifie tout ce qui lui passe entre les mains",
      "garde un carnet de croquis techniques",
      "teste les objets en les secouant",
      "démonte un appareil neuf par curiosité",
      "note les références des pièces qui le passionnent",
      "bricole même quand rien n'est cassé",
      "range ses outils dans un ordre connu de lui seul",
      "juge un véhicule au bruit du moteur",
      "récupère la ferraille des autres",
      "parle boulot dès qu'on le laisse faire",
      "gratte une tache de graisse en réfléchissant",
    ],
    civil: [
      "évite les ennuis à tout prix",
      "parle de sa famille",
      "compte les heures avant la fin du service",
      "consulte les horaires de transport",
      "parle de son travail même hors service",
      "vérifie ses dépenses",
      "évite les sujets dangereux",
      "range ses reçus soigneusement",
      "s'excuse même quand ce n'est pas sa faute",
      "planifie ses courses pour économiser",
      "raconte les potins du voisinage",
      "vérifie deux fois avant de signer",
      "garde une petite réserve pour les imprévus",
      "salue poliment tout le monde",
      "s'inquiète de ce que penseront les autres",
      "rêve à voix haute de vacances lointaines",
      "coupe court dès qu'une histoire tourne mal",
      "compte les jours avant la paie",
      "garde la tête basse devant l'autorité",
      "vérifie que la porte est bien fermée deux fois",
      "parle météo pour éviter le reste",
      "note les bonnes affaires du quartier",
      "évite de croiser le regard des inconnus",
      "remercie pour un rien, par principe",
      "se plaint doucement des transports",
    ],
  },

  _motivations: {
    any: [
      "payer ses dettes",
      "survivre une nuit de plus",
      "se faire un nom",
      "protéger les siens",
      "oublier un passé qui colle à la peau",
      "prouver qu'on s'est trompé à son sujet",
      "obtenir enfin des réponses",
      "quitter cette ville pour toujours",
      "retrouver quelqu'un disparu",
      "gagner suffisamment pour recommencer ailleurs",
      "tenir une promesse faite autrefois",
      "effacer une erreur qui le hante",
      "protéger un secret coûte que coûte",
      "rembourser quelqu'un qui a cru en lui",
      "se racheter aux yeux d'un proche",
      "mettre de côté pour un avenir meilleur",
      "retrouver une trace de son passé",
      "tenir jusqu'au bout de la semaine",
      "gagner le respect qu'on lui refuse",
      "sortir un être cher d'une mauvaise passe",
      "prouver qu'il vaut mieux que sa réputation",
      "s'offrir enfin un peu de tranquillité",
      "réparer une injustice ancienne",
      "ne plus jamais avoir faim",
      "trouver un endroit qu'il pourrait appeler chez lui",
      "honorer la mémoire de quelqu'un",
      "reprendre le contrôle de sa vie",
    ],
    gang: [
      "défendre le territoire",
      "venger un frère tombé",
      "monter dans la hiérarchie du gang",
      "prouver sa valeur",
      "sortir un proche du gang",
      "récupérer un territoire perdu",
      "éviter une guerre de gangs",
      "gagner assez pour quitter les Barrens",
      "faire respecter les couleurs",
      "grimper jusqu'au sommet du gang",
      "protéger le petit frère de la rue",
      "reprendre le bloc perdu aux rivaux",
      "se venger d'une humiliation publique",
      "prouver qu'il n'a peur de personne",
      "financer la survie de sa bande",
      "devenir une légende du quartier",
      "sortir sa famille des Barrens",
      "régler ses comptes avec un ancien",
      "tenir le territoire coûte que coûte",
      "gagner de quoi s'offrir du vrai chrome",
      "éviter la guerre ouverte avec les voisins",
      "venger un membre tombé",
      "s'imposer face à un chef contesté",
      "protéger un dealer qui rapporte",
    ],
    corpo: [
      "décrocher une promotion",
      "ne pas finir comme variable d'ajustement",
      "rembourser son contrat",
      "plaire au supérieur direct",
      "survivre à la prochaine restructuration",
      "obtenir un bureau au bon étage",
      "effacer une erreur de carrière",
      "échapper à une clause contractuelle",
      "faire oublier un scandale interne",
      "monter dans une mégacorpo AAA",
      "négocier une prime de départ confortable",
      "éviter de finir sur une liste de liquidation",
      "sécuriser la prochaine promotion",
      "écraser un rival de service",
      "racheter sa clause de non-concurrence",
      "obtenir un poste à l'étranger",
      "faire disparaître une note défavorable",
      "gagner la confiance d'un supérieur clé",
      "atteindre ses objectifs trimestriels",
      "détourner discrètement un budget",
      "protéger sa place lors des coupes",
      "grimper au comité de direction",
      "négocier un parachute doré",
      "faire tomber un concurrent interne",
      "préserver un secret compromettant",
      "obtenir le badge d'accès supérieur",
      "monnayer une information sensible",
      "s'assurer une retraite dorée",
    ],
    police: [
      "nettoyer son secteur",
      "boucler son service sans bavure",
      "arrondir ses fins de mois",
      "coffrer une cible précise",
      "prouver qu'une affaire a été étouffée",
      "protéger ses équipiers",
      "prendre sa retraite vivant",
      "faire tomber quelqu'un d'intouchable",
      "boucler l'affaire de sa carrière",
      "coincer un truand insaisissable",
      "protéger un indic précieux",
      "arrondir discrètement ses fins de mois",
      "laver l'honneur d'un collègue",
      "démanteler un réseau bien protégé",
      "survivre jusqu'à la retraite",
      "faire tomber un ripou haut placé",
      "venger un partenaire abattu",
      "garder le contrôle de son secteur",
      "obtenir une mutation méritée",
      "boucler son quota d'arrestations",
      "prouver qu'une affaire a été étouffée",
      "récupérer une preuve disparue",
      "éviter une bavure de plus",
      "sauver sa plaque d'une enquête interne",
    ],
    crime: [
      "honorer la famille",
      "étendre le racket",
      "effacer un témoin gênant",
      "rembourser un parrain",
      "maintenir la paix entre deux familles",
      "préparer sa succession",
      "faire payer une trahison ancienne",
      "préserver les apparences",
      "monter en grade auprès de l'oyabun",
      "récupérer une cargaison détournée",
      "blanchir un magot en nuyens sales",
      "asseoir l'autorité de la famille",
      "éliminer un traître discrètement",
      "prendre le contrôle d'un nouveau racket",
      "rembourser une dette d'honneur",
      "préparer sa succession en douceur",
      "faire payer une trahison ancienne",
      "protéger une route de contrebande",
      "acheter le silence d'un juge",
      "monter en grade auprès du parrain",
      "récupérer un magot détourné",
      "sceller une alliance rentable",
      "éliminer la concurrence sur son territoire",
      "sauver les apparences après un fiasco",
      "venger un capo abattu",
      "étendre l'emprise sur un quartier",
      "récupérer une cargaison détournée",
    ],
    militaire: [
      "accomplir la mission",
      "ramener son équipe vivante",
      "toucher sa prime",
      "fuir un passé de soldat",
      "retrouver un ancien frère d'armes",
      "oublier une opération qui a mal tourné",
      "racheter une erreur de commandement",
      "prouver qu'il est encore utile",
      "décrocher un contrat de merco bien payé",
      "mener la mission à son terme",
      "ramener tout le monde vivant",
      "toucher enfin sa prime de contrat",
      "fuir un passé de champ de bataille",
      "retrouver un frère d'armes disparu",
      "racheter une opération qui a mal tourné",
      "prouver qu'il est encore le meilleur",
      "oublier des ordres qu'il regrette",
      "protéger des civils cette fois-ci",
      "obtenir une réhabilitation officielle",
      "venger une unité décimée",
      "s'assurer une solde qui vaut le risque",
      "reprendre du service pour une bonne cause",
      "tenir la position quoi qu'il en coûte",
      "récupérer du matériel volé à l'armée",
      "en finir avec les cauchemars de guerre",
    ],
    rue: [
      "trouver un repas chaud",
      "un toit pour la nuit",
      "une dose",
      "ne pas se faire remarquer",
      "obtenir un vrai SIN",
      "mettre quelqu'un à l'abri",
      "trouver un endroit sûr",
      "rester invisible aux autorités",
      "se payer un soykaf bien chaud",
      "échapper à la Star encore une fois",
      "trouver un repas chaud ce soir",
      "un toit avant la nuit",
      "de quoi tenir un jour de plus",
      "se procurer un vrai SIN",
      "mettre un proche à l'abri",
      "échapper aux rafles de la Star",
      "trouver un coin sûr pour dormir",
      "gagner de quoi payer une dose",
      "rester invisible aux autorités",
      "sortir enfin de la rue",
      "protéger les siens du froid",
      "se refaire une santé",
      "économiser pour un billet loin d'ici",
      "trouver quelqu'un à qui faire confiance",
      "éviter les ennuis encore une nuit",
      "récupérer ce qu'on lui a volé",
    ],
    ombre: [
      "le prochain gros coup",
      "disparaître pour de bon",
      "régler une vieille dette",
      "rester intraçable",
      "amasser assez d'argent pour disparaître",
      "tenir jusqu'au prochain contrat",
      "protéger une identité secrète",
      "quitter définitivement les Ombres",
      "honorer le contrat d'un M. Johnson généreux",
      "se constituer un magot en nuyens",
      "se forger une vraie réputation, de la créd",
      "réussir le run qui changera tout",
      "trouver un intermédiaire qui paie rubis sur l'ongle",
      "réussir le run qui changera tout",
      "monter une équipe de confiance",
      "solder ses comptes avec un ancien employeur",
      "effacer une trace compromettante",
      "mettre un magot de côté à l'abri",
      "protéger une identité de secours",
      "trouver un fixer vraiment fiable",
      "raccrocher avant le coup de trop",
      "se forger une vraie réputation de pro",
      "doubler un Johnson qui l'a doublé",
      "retrouver un équipier porté disparu",
      "obtenir des faux papiers en béton",
      "boucler un dernier gros contrat",
      "disparaître avant que le passé le rattrape",
      "récupérer un paydata mis en gage",
      "rembourser une dette envers un fixer",
    ],
    magique: [
      "percer un mystère astral",
      "honorer son mentor/totem",
      "maîtriser un pouvoir qui le dépasse",
      "protéger un lieu sacré",
      "comprendre une vision récurrente",
      "apaiser un esprit hostile",
      "retrouver un artefact disparu",
      "éviter une catastrophe annoncée",
      "satisfaire les exigences de son Esprit mentor",
      "maîtriser le Drain de ses sorts les plus puissants",
      "approfondir les secrets de sa Tradition",
      "restaurer un équilibre rompu",
      "gagner la faveur d'un esprit puissant",
      "empêcher une profanation",
      "déchiffrer un grimoire interdit",
      "expier une faute magique passée",
      "protéger un novice de ses propres pouvoirs",
      "retrouver un mentor disparu",
      "sceller une brèche vers l'astral",
      "obtenir la reconnaissance d'un cercle d'initiés",
      "dompter un totem exigeant",
      "guérir une blessure d'âme",
      "récupérer une relique volée à sa loge",
      "percer le secret d'une malédiction",
      "atteindre un degré d'initiation supérieur",
      "apaiser les esprits d'un lieu hanté",
      "conjurer une prophétie funeste",
    ],
    matrice: [
      "la donnée parfaite",
      "humilier une corpo",
      "effacer son propre dossier",
      "le frisson de l'intrusion",
      "publier des données interdites",
      "dévoiler un secret corporatiste",
      "devenir une légende de la Matrice",
      "retrouver des données effacées",
      "décrocher le butin numérique du siècle",
      "franchir une glace réputée infranchissable",
      "venger un ami victime d'un choc d'éjection",
      "effacer son icône des serveurs de la Star",
      "narguer DIEU et survivre à la Convergence",
      "garder son Score de Surveillance au plus bas",
      "libérer une IA emprisonnée",
      "pirater le réseau qu'on dit inviolable",
      "monnayer un paydata explosif",
      "démasquer un espion sur la Matrice",
      "bâtir la légende de son pseudo",
      "faire tomber un forum de la Star",
      "récupérer des souvenirs numériques effacés",
      "coder le virus parfait",
      "s'introduire dans un hôte fondation d'une AAA",
      "effacer les preuves d'un run raté",
      "venger un ami victime d'un choc d'éjection",
      "cartographier un serveur secret",
      "revendre un accès en or à prix fort",
      "narguer une IA de sécurité et survivre",
      "récupérer son icône saisie par DIEU",
      "protéger un lanceur d'alerte en ligne",
    ],
    tech: [
      "construire la machine parfaite",
      "récupérer des pièces rares",
      "prouver son génie",
      "un atelier à soi",
      "mettre au point une invention impossible",
      "ouvrir son propre atelier",
      "réparer quelque chose qu'il a détruit",
      "être reconnu pour son talent",
      "sortir un drone unique de sa carcasse",
      "transformer une épave en bijou de chrome",
      "breveter une trouvaille avant les autres",
      "rassembler assez pour monter son garage",
      "concevoir le véhicule ultime",
      "remettre en marche une antiquité",
      "surpasser un rival ingénieur",
      "financer un projet un peu fou",
      "dénicher une pièce introuvable",
      "réparer ce qu'il a lui-même détruit",
      "être enfin reconnu pour son talent",
      "assembler un drone unique en son genre",
      "récupérer un prototype abandonné",
      "monter un atelier bien à lui",
      "battre un record de bricolage improbable",
      "sauver une machine que tous croyaient perdue",
      "vendre une invention à bon prix",
      "former un apprenti digne de ce nom",
    ],
    civil: [
      "nourrir sa famille",
      "garder son emploi",
      "une vie tranquille",
      "éviter les runners",
      "payer les études d'un enfant",
      "conserver son logement",
      "échapper à ses dettes",
      "rester en dehors des problèmes des autres",
      "offrir un meilleur avenir aux siens",
      "tenir jusqu'à la fin du mois",
      "obtenir une petite augmentation",
      "protéger sa famille des mauvaises fréquentations",
      "réaliser un vieux rêve modeste",
      "rembourser un crédit qui l'étouffe",
      "sortir son quartier de la misère",
      "juste passer inaperçu",
      "économiser pour un logement décent",
      "garder ses enfants loin des gangs",
      "décrocher un emploi plus stable",
      "s'offrir enfin de vraies vacances",
      "protéger son petit commerce",
      "éviter que la corpo le remarque",
      "aider un voisin dans le besoin",
      "retrouver une vie normale",
    ],
  },

  _styles: {
    any: [
      "pragmatique",
      "discret",
      "tape-à-l'œil",
      "minimaliste",
      "usé mais entretenu",
      "fonctionnel avant tout",
      "délibérément intimidant",
      "élégance négligée",
      "rétro remis au goût du jour",
      "personnalisé jusqu'à l'excès",
      "sobre et fonctionnel",
      "coloré sans excès",
      "usé jusqu'à la corde mais propre",
      "assemblage hétéroclite",
      "classique indémodable",
      "pratique avant tout",
      "discrètement soigné",
      "récup' assumée",
      "neutre et oubliable",
      "marqué par une pièce fétiche",
      "seconde main retapée",
      "confortable avant esthétique",
      "sombre de la tête aux pieds",
      "bariolé et dépareillé",
      "minimaliste jusqu'à la froideur",
      "customisé pièce par pièce",
    ],

    gang: [
      "fringues de rue couvertes d'écussons",
      "cuir clouté",
      "couleurs criardes du gang",
      "allure d'après-guerre des Barrens",
      "mode urbaine agressive",
      "équipement de récupération bricolé",
      "style inspiré des icônes du gang",
      "mélange de vêtements volés et de trophées",
      "ostentation des augmentations",
      "allure de prédateur de quartier",
      "cuir couvert d'écussons",
      "couleurs voyantes du gang",
      "denim taillé et clouté",
      "capuche et bandana assortis",
      "baskets de luxe volées",
      "bijoux clinquants de récup",
      "veste sans manches couverte de patchs",
      "mode urbaine agressive",
      "trophées cousus sur les vêtements",
      "chrome exhibé sans complexe",
      "look de prédateur de bloc",
      "tatouages laissés bien visibles",
      "vêtements marqués au blaze",
      "style inspiré d'une icône du gang",
      "allure de guerrier des Barrens",
      "accessoires détournés en armes",
    ],

    corpo: [
      "costume taillé sur mesure",
      "tailleur sobre et cher",
      "tenue corpo augmentée RA",
      "élégance froide",
      "luxe discret",
      "mode corporatiste de dernière génération",
      "tenue pensée pour impressionner",
      "sobriété calculée",
      "apparence calibrée par le service image",
      "style de cadre supérieur inaccessible",
      "tailleur cintré haut de gamme",
      "costume trois pièces sans un pli",
      "palette de gris et de bleu marine",
      "accessoires de marque discrets",
      "tenue RA à affichage intégré",
      "élégance clinique",
      "luxe qui ne se montre pas",
      "coupe dernier cri de la saison",
      "sobriété étudiée par un service image",
      "chaussures qui valent un mois de loyer",
      "apparence lissée jusqu'au moindre détail",
      "style de dirigeant intouchable",
      "manteau long impeccable",
      "montre-bijou comme seule fantaisie",
      "tissu technique haut de gamme",
      "allure calibrée pour rassurer",
    ],

    police: [
      "uniforme réglementaire",
      "armure de patrouille",
      "civil mais reconnaissable",
      "imperméable de détective",
      "tenue pratique et robuste",
      "ancien uniforme conservé par habitude",
      "style de flic hors service",
      "équipement toujours à portée de main",
      "allure de vétéran de la rue",
      "fonctionnel jusqu'à l'austérité",
      "uniforme réglementaire repassé",
      "armure de patrouille éraflée",
      "civil mais reconnaissable au premier coup d'œil",
      "imperméable de vieux limier",
      "tenue robuste pensée pour l'action",
      "ancien uniforme reconverti",
      "look de flic même hors service",
      "équipement toujours à portée",
      "allure de vétéran de la rue",
      "veste tactique sombre",
      "chaussures faites pour courir",
      "insigne discret mais présent",
      "coupe stricte et pratique",
      "tenue sobre qui inspire l'autorité",
      "pièces d'équipement dépareillées mais efficaces",
      "gilet pare-balles sous la veste",
    ],

    crime: [
      "complet sombre soigné",
      "bijoux ostentatoires",
      "élégance menaçante",
      "sobre mais coûteux",
      "luxe de mauvais goût",
      "apparence de notable respectable",
      "raffinement intimidant",
      "mode traditionnelle de la famille",
      "richesse affichée comme une arme",
      "costume conçu pour dissimuler une arme",
      "complet sombre parfaitement coupé",
      "bijoux ostentatoires assumés",
      "élégance qui sent la menace",
      "sobre mais hors de prix",
      "luxe volontairement voyant",
      "apparence de notable respectable",
      "raffinement intimidant",
      "tenue traditionnelle de la famille",
      "richesse portée comme une armure",
      "chapeau et manteau d'un autre âge",
      "chevalière et montre en or",
      "cravate de soie impeccable",
      "allure de patriarche redouté",
      "sobriété trompeuse du fixer",
      "élégance sombre de la pègre",
      "chaussures italiennes cousues main",
    ],

    militaire: [
      "treillis et armure modulaire",
      "surplus militaire",
      "tenue tactique noire",
      "camouflage urbain",
      "équipement entretenu avec obsession",
      "ancien uniforme adapté à la vie civile",
      "allure de mercenaire professionnel",
      "prêt au combat en permanence",
      "style austère et réglementaire",
      "matériel avant apparence",
      "rangers cirées et pantalon renforcé",
      "veste couverte de poches utiles",
      "gilet tactique porté au quotidien",
      "sobriété fonctionnelle du soldat",
      "gants et lunettes de combat à portée",
      "tenue pensée pour durer sous le feu",
      "camouflage urbain discret",
      "surplus militaire recyclé",
      "look de mercenaire aguerri",
      "prêt au combat en permanence",
      "treillis délavé mais impeccable",
      "ceinturon lourd d'équipement",
      "bottes de combat éprouvées",
      "veste kaki sans insigne",
      "harnais tactique sous le manteau",
      "style réglementaire jusqu'au bout",
    ],

    rue: [
      "fripes superposées",
      "vêtements de récup",
      "manteau rapiécé",
      "allure crasseuse mais fonctionnelle",
      "assemblage de dons et de trouvailles",
      "plusieurs couches contre le froid et la pluie",
      "tenue adaptée à la survie urbaine",
      "vêtements trop grands récupérés ailleurs",
      "apparence volontairement invisible",
      "style des squats et des refuges",
      "chaussures rembourrées de carton",
      "capuche et écharpe cachant le visage",
      "sac contenant toute une vie",
      "gants coupés et bonnet enfoncé",
      "vêtements marqués par les intempéries",
      "look de survivant des rues",
      "manteau troué mais chaud",
      "assemblage de dons et de trouvailles",
      "plusieurs couches dépareillées",
      "fripes superposées contre le froid",
      "tenue grise pour ne pas être vu",
      "semelles rafistolées au ruban adhésif",
      "vieux blouson trop grand",
      "poches bourrées de petites réserves",
      "vêtements lavés dans les fontaines",
      "allure de fantôme du bitume",
    ],

    ombre: [
      "tenue passe-partout sombre",
      "vêtements sans marque ni signe",
      "gris urbain",
      "noir technique discret",
      "mode qui ne retient pas l'attention",
      "équipement dissimulé dans les vêtements",
      "élégance utilitaire",
      "allure interchangeable",
      "style de professionnel prudent",
      "apparence conçue pour disparaître dans la foule",
      "manteau réversible aux teintes neutres",
      "chaussures souples et silencieuses",
      "aucun détail mémorable",
      "vêtements adaptés à chaque quartier",
      "coupe sobre facile à oublier",
      "accessoires discrets et fonctionnels",
      "gris urbain anonyme",
      "noir technique discret",
      "silhouette interchangeable",
      "style de professionnel prudent",
      "capuche neutre relevée sans excès",
      "tissus mats qui n'accrochent pas la lumière",
      "gants fins toujours à portée",
      "veste sans logo ni motif",
      "tenue pensée pour tromper les caméras",
      "élégance strictement utilitaire",
    ],

    magique: [
      "robes et fétiches",
      "allure mystique discrète",
      "vêtements ornés de symboles",
      "sobriété chargée de sens",
      "tenues traditionnelles adaptées au Sixième Monde",
      "bijoux rituels omniprésents",
      "style ésotérique contemporain",
      "vêtements choisis selon des considérations symboliques",
      "apparence d'érudit occulte",
      "mélange de spiritualité et de modernité",
      "amulettes visibles à chaque poignet",
      "couleurs choisies selon la Tradition",
      "capuche et pendentifs anciens",
      "tissus naturels refusant le synthétique",
      "peintures rituelles sur la peau",
      "allure de chaman des villes",
      "robes ornées de fétiches",
      "vêtements couverts de symboles",
      "sobriété chargée de sens",
      "style ésotérique contemporain",
      "apparence d'érudit occulte",
      "colliers de perles et d'osselets",
      "châle brodé de motifs anciens",
      "bijoux gravés de glyphes",
      "tenue traditionnelle revisitée",
      "accessoires rituels portés en évidence",
    ],

    matrice: [
      "sweat à capuche et lunettes RA",
      "allure de hacker négligé",
      "tenue confortable bardée de tech",
      "néo-cyberpunk",
      "vêtements saturés d'interfaces",
      "mode urbaine augmentée",
      "allure d'insomniaque chronique",
      "câbles, batteries et accessoires apparents",
      "minimalisme technologique",
      "style influencé par les célébrités de la Matrice",
      "veste couverte de ports et de prises",
      "baskets clignotant de LED",
      "capuche baissée sur des lunettes teintées",
      "accessoires geek assumés",
      "tenue sombre piquée de néons",
      "look de rat de datahaven",
      "sweat à capuche et lunettes RA",
      "vêtements saturés d'interfaces",
      "mode urbaine augmentée",
      "câbles et batteries apparents",
      "minimalisme technologique",
      "allure d'insomniaque chronique",
      "t-shirt à l'effigie d'un vieux jeu",
      "poches pleines de puces et de câbles",
      "gants tactiles aux doigts usés",
      "look néo-cyberpunk négligé",
    ],

    tech: [
      "combinaison de mécano",
      "veste à mille poches",
      "tablier renforcé",
      "tenue pratique tachée d'huile",
      "équipement modifié maison",
      "style d'atelier permanent",
      "vêtements renforcés contre les accidents",
      "accessoires techniques omniprésents",
      "apparence de bricoleur obsessionnel",
      "fonctionnalité absolue",
      "gants de travail et lunettes relevées",
      "ceinture porte-outils bien remplie",
      "bleu de travail constellé de brûlures",
      "chaussures de sécurité éraflées",
      "poches débordant de gadgets",
      "look de rigger toujours en intervention",
      "combinaison de mécano tachée",
      "veste à mille poches",
      "tablier de cuir renforcé",
      "équipement modifié maison",
      "style d'atelier permanent",
      "vêtements renforcés contre les accidents",
      "casquette vissée et crayon sur l'oreille",
      "manches retroussées maculées d'huile",
      "genouillères usées par le travail au sol",
      "accessoires techniques omniprésents",
    ],

    civil: [
      "vêtements de tous les jours",
      "tenue de travail",
      "allure ordinaire et passe-partout",
      "style de salarié fatigué",
      "mode achetée en grande surface",
      "vêtements choisis pour durer",
      "apparence soigneuse malgré les moyens limités",
      "allure de parent débordé",
      "sobriété économique",
      "allure sans histoire",
      "pull confortable et jean usé",
      "veste correcte gardée des années",
      "chaussures pratiques bon marché",
      "tenue propre mais démodée",
      "look discret de la classe moyenne",
      "vêtements repassés de frais",
      "vêtements de tous les jours",
      "tenue de travail passe-partout",
      "mode achetée en grande surface",
      "apparence soignée malgré les moyens",
      "allure de parent débordé",
      "sobriété économique",
      "manteau simple et sans marque",
      "sac à dos usé de la vie quotidienne",
      "couleurs ternes et rassurantes",
      "style effacé de qui veut passer inaperçu",
    ],
  },

  _attitudes: {
    any: [
      "méfiant mais poli",
      "fatigué et pressé",
      "chaleureux en apparence",
      "sur la défensive",
      "curieux",
      "agressivement amical",
      "observe avant de parler",
      "cherche à évaluer son interlocuteur",
      "semble constamment préoccupé",
      "agit comme s'il manquait de temps",
      "poli mais impossible à cerner",
      "affiche une neutralité prudente",
      "évalue son interlocuteur en silence",
      "sympathique juste ce qu'il faut",
      "garde ses distances par principe",
      "répond franchement mais brièvement",
      "montre une patience feinte",
      "cherche discrètement ses intérêts",
      "reste courtois même tendu",
      "donne peu, écoute beaucoup",
      "affable en surface, méfiant en dessous",
      "attend de voir avant de s'engager",
      "réagit avec un temps de retard calculé",
      "pèse chaque mot",
      "reste sur la réserve",
    ],

    gang: [
      "cherche à intimider",
      "teste immédiatement les limites",
      "joue les gros bras",
      "traite les inconnus comme des rivaux potentiels",
      "protège instinctivement les siens",
      "affiche une confiance excessive",
      "réagit vite aux provocations",
      "cherche le respect avant tout",
      "cherche à impressionner d'emblée",
      "teste les limites tout de suite",
      "prend tout de haut",
      "traite chaque inconnu comme un rival",
      "protège les siens sans réfléchir",
      "affiche une assurance excessive",
      "s'enflamme à la moindre provocation",
      "exige du respect avant tout dialogue",
      "bombe le torse par habitude",
      "cherche l'approbation de sa bande",
      "répond à l'insulte par l'insulte",
      "montre les crocs pour un rien",
      "juge les gens à leur cran",
      "se braque dès qu'on le questionne",
      "cherche la baston pour se prouver",
    ],

    corpo: [
      "professionnel et distant",
      "aimablement condescendant",
      "sourit sans se dévoiler",
      "considère chaque échange comme une négociation",
      "cherche à garder le contrôle",
      "parle comme en réunion",
      "traite les émotions comme un problème à résoudre",
      "évalue immédiatement l'utilité des gens",
      "professionnel et distant",
      "aimablement condescendant",
      "sourit sans jamais se livrer",
      "traite tout comme une négociation",
      "cherche à garder le contrôle",
      "parle comme en réunion",
      "considère les émotions comme un obstacle",
      "reste courtois avec une pointe de mépris",
      "garde une longueur d'avance dans l'échange",
      "reformule tout à son avantage",
      "affiche une assurance étudiée",
      "coupe court dès que ça n'est plus rentable",
      "flatte quand ça sert ses intérêts",
      "traite les gens comme des variables",
      "évalue le coût de chaque faveur",
    ],

    police: [
      "pose des questions avant de répondre",
      "reste constamment vigilant",
      "cherche les incohérences",
      "agit comme en service",
      "considère tout le monde comme un suspect potentiel",
      "essaie de garder la situation sous contrôle",
      "affiche une autorité naturelle",
      "s'attend au pire",
      "questionne avant de répondre",
      "reste vigilant en permanence",
      "traque la moindre incohérence",
      "agit comme s'il était en service",
      "prend chacun pour un suspect potentiel",
      "cherche à garder la main sur la situation",
      "affiche une autorité naturelle",
      "jauge la culpabilité dans les regards",
      "note tout, mine de rien",
      "impose son rythme à l'échange",
      "reste imperturbable sous la pression",
      "pousse dans ses retranchements avec calme",
      "garde un ton neutre d'interrogatoire",
      "ne lâche rien une fois lancé",
      "cherche le mensonge derrière chaque sourire",
    ],

    crime: [
      "parle calmement pour inquiéter",
      "traite chaque échange comme une dette",
      "semble toujours connaître un secret",
      "accorde sa confiance au compte-gouttes",
      "cherche les leviers de pression",
      "donne l'impression d'être dangereux sans hausser le ton",
      "valorise le respect et les formes",
      "laisse volontairement planer la menace",
      "parle bas pour mieux inquiéter",
      "traite chaque échange comme une dette",
      "semble toujours détenir un secret",
      "n'accorde sa confiance qu'au compte-gouttes",
      "cherche les leviers de pression",
      "paraît dangereux sans hausser le ton",
      "attache de l'importance aux formes",
      "sourit poliment en pesant sa cible",
      "récompense la déférence",
      "punit la familiarité d'un regard froid",
      "prend son temps, toujours",
      "fait sentir qui commande sans le dire",
      "garde un calme qui met mal à l'aise",
      "n'oublie ni un service ni un affront",
      "laisse un silence répondre à sa place",
    ],

    militaire: [
      "analyse la situation avant les personnes",
      "reste discipliné même au repos",
      "donne des ordres sans s'en rendre compte",
      "cherche une chaîne de commandement",
      "considère les problèmes comme des objectifs",
      "garde ses émotions sous contrôle",
      "privilégie l'efficacité à la diplomatie",
      "agit comme si le danger pouvait surgir à tout moment",
      "analyse la situation avant les gens",
      "reste discipliné même détendu",
      "donne des ordres sans s'en rendre compte",
      "cherche instinctivement une hiérarchie",
      "traite les problèmes comme des objectifs",
      "garde ses émotions verrouillées",
      "privilégie l'efficacité à la diplomatie",
      "évalue chacun comme un atout ou un risque",
      "communique par phrases courtes",
      "attend des réponses claires et nettes",
      "supporte mal l'imprécision",
      "garde son sang-froid quand tout dérape",
      "juge les gens à leur fiabilité sous pression",
      "reste maître de lui en toute situation",
      "sécurise la pièce avant de se détendre",
    ],

    rue: [
      "s'attend à être trompé",
      "reste prêt à fuir",
      "se montre reconnaissant au moindre geste",
      "cherche à éviter les conflits",
      "parle peu et écoute beaucoup",
      "craint les autorités",
      "attend qu'on lui demande quelque chose en retour",
      "se méfie des gens trop gentils",
      "s'attend à être trompé",
      "reste prêt à détaler",
      "se montre reconnaissant au moindre geste",
      "cherche à éviter tout conflit",
      "parle peu et écoute beaucoup",
      "craint instinctivement les autorités",
      "attend toujours une contrepartie",
      "baisse les yeux par prudence",
      "flaire l'arnaque à distance",
      "reste sur ses gardes même détendu",
      "remercie avec une gêne visible",
      "se fait tout petit face aux plus forts",
      "guette la moindre occasion",
      "hésite avant d'accorder sa confiance",
      "garde un œil sur la sortie la plus proche",
    ],

    ombre: [
      "évalue chaque mot prononcé",
      "agit comme si la réunion était déjà terminée",
      "ne révèle jamais plus que nécessaire",
      "semble constamment prévoir une sortie",
      "fait parler les autres",
      "garde une distance émotionnelle",
      "reste calme même sous pression",
      "donne l'impression d'avoir déjà vécu cette situation",
      "évalue chaque mot prononcé",
      "agit comme si la réunion était déjà finie",
      "ne révèle jamais plus que nécessaire",
      "semble toujours prévoir une sortie",
      "fait parler les autres",
      "garde une distance émotionnelle",
      "reste calme même sous pression",
      "répond à côté pour ne rien livrer",
      "observe plus qu'il ne parle",
      "cache ses intentions derrière une politesse lisse",
      "jauge chacun comme une menace ou un atout",
      "ne s'engage jamais sans porte de sortie",
      "reste maître de ses réactions",
      "laisse un silence en dire plus que des mots",
      "vérifie qui écoute avant de parler",
    ],

    magique: [
      "semble savoir quelque chose que les autres ignorent",
      "écoute des choses invisibles",
      "considère les événements comme des signes",
      "réagit à des détails insignifiants",
      "parle parfois de façon énigmatique",
      "reste calme face à l'inexplicable",
      "accorde de l'importance aux symboles",
      "semble observer plusieurs réalités à la fois",
      "semble savoir ce que d'autres ignorent",
      "écoute des choses invisibles",
      "prend les événements pour des signes",
      "réagit à des détails insignifiants",
      "parle parfois par énigmes",
      "reste serein face à l'inexplicable",
      "accorde du poids aux symboles",
      "s'exprime avec une lenteur pensée",
      "traite les coïncidences comme des messages",
      "garde une distance presque mystique",
      "fixe l'invisible par instants",
      "répond aux questions qu'on n'a pas posées",
      "semble en dialogue avec l'absent",
      "affiche un calme qui déstabilise",
      "sonde les gens comme on lit une aura",
    ],

    matrice: [
      "paraît distrait par des informations invisibles",
      "réfléchit plus vite qu'il ne parle",
      "considère les gens comme des systèmes",
      "semble plus à l'aise en RA qu'en face-à-face",
      "passe brutalement d'un sujet à l'autre",
      "traite les problèmes comme des énigmes techniques",
      "cherche des données avant des opinions",
      "oublie parfois le monde physique",
      "paraît distrait par des données invisibles",
      "réfléchit plus vite qu'il ne parle",
      "voit les gens comme des systèmes",
      "semble plus à l'aise en RA qu'en vrai",
      "saute brutalement d'un sujet à l'autre",
      "aborde tout comme une énigme technique",
      "cherche des données avant des opinions",
      "répond en décalé, l'esprit ailleurs",
      "s'anime dès qu'on parle de tech",
      "traite la conversation comme un flux à filtrer",
      "coupe court à l'imprécision",
      "évalue la fiabilité comme celle d'un logiciel",
      "perd patience avec la lenteur des autres",
      "garde un œil sur des fenêtres que nul ne voit",
      "se méfie de tout ce qui n'est pas chiffré",
    ],

    tech: [
      "cherche à comprendre avant d'agir",
      "voit des problèmes à réparer partout",
      "préfère les machines aux gens",
      "aborde les difficultés de façon méthodique",
      "reste calme face aux pannes et au chaos",
      "s'intéresse davantage aux objets qu'aux propriétaires",
      "veut toujours améliorer ce qui fonctionne déjà",
      "réfléchit à voix haute",
      "cherche à comprendre avant d'agir",
      "voit partout des choses à réparer",
      "préfère les machines aux gens",
      "aborde les problèmes avec méthode",
      "reste calme face aux pannes et au chaos",
      "s'intéresse aux objets plus qu'à leurs propriétaires",
      "veut toujours améliorer l'existant",
      "démonte mentalement tout ce qu'il voit",
      "explique volontiers, parfois trop",
      "juge les gens à leur logique",
      "s'impatiente devant l'inefficacité",
      "reste concentré même dans le vacarme",
      "cherche la cause plutôt que le coupable",
      "aborde chaque souci comme un défi technique",
      "fait davantage confiance aux outils qu'aux mots",
    ],

    civil: [
      "cherche avant tout à éviter les ennuis",
      "essaie de rester poli",
      "s'inquiète des conséquences",
      "fait passer sa famille avant tout",
      "espère que tout rentrera dans l'ordre",
      "se montre prudent avec les inconnus",
      "préfère les compromis aux conflits",
      "semble dépassé par les événements",
      "cherche avant tout à éviter les ennuis",
      "essaie de rester poli en toute circonstance",
      "s'inquiète des conséquences",
      "fait passer sa famille avant tout",
      "espère que tout rentrera dans l'ordre",
      "reste prudent avec les inconnus",
      "préfère les compromis aux conflits",
      "baisse le ton dès que ça monte",
      "cherche l'approbation générale",
      "évite de prendre parti",
      "s'excuse pour désamorcer",
      "regarde ailleurs quand ça tourne mal",
      "veut juste rentrer chez lui tranquille",
      "fait profil bas devant plus fort que lui",
      "espère ne surtout pas se faire remarquer",
    ],
  },

  _pick(pool, tags) {
    // Concatène les pools des tags présents + le fond commun, puis tire
    let bag = [...(pool.any || [])];
    for (const t of tags) if (pool[t]) bag = bag.concat(pool[t]);
    return Utils.rand(bag);
  },

  /* ----------------------------------------------------------
     APPLICATION — enrichit le PNJ. Idempotent : si pnj.flavor
     existe déjà (édition manuelle), on ne l'écrase pas.
  ---------------------------------------------------------- */
  apply(pnj) {
    if (!pnj || pnj.flavor) return pnj;
    const tags = this.tagsFor(pnj);
    pnj.flavor = {
      age: this._ageFor(pnj),
      signe: this._pick(this._signes, tags),
      manie: this._pick(this._manies, tags),
      motivation: this._pick(this._motivations, tags),
      style: this._pick(this._styles, tags),
      attitude: this._pick(this._attitudes, tags),
    };
    return pnj;
  },

  /** Re-tirage manuel d'un champ (pour un bouton « relancer » futur) */
  reroll(pnj, field) {
    const tags = this.tagsFor(pnj);
    const map = {
      signe: this._signes,
      manie: this._manies,
      motivation: this._motivations,
      style: this._styles,
      attitude: this._attitudes,
    };
    if (field === "age") pnj.flavor.age = this._ageFor(pnj);
    else if (map[field]) pnj.flavor[field] = this._pick(map[field], tags);
    return pnj;
  },
};
